# Generated by Django 3.1.4 on 2021-01-19 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subcategories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1024)),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to='images/', width_field='width_field')),
                ('height_field', models.IntegerField(blank=True, default=0, null=True)),
                ('width_field', models.IntegerField(blank=True, default=0, null=True)),
                ('price', models.FloatField(default=0)),
                ('in_stock', models.BooleanField(blank=True, default=True, null=True)),
                ('discount', models.BooleanField(blank=True, default=False, null=True)),
                ('discount_description', models.TextField(blank=True, default=0, max_length=512, null=True)),
                ('discount_price', models.FloatField(blank=True, default=0, null=True)),
                ('discount_percent', models.IntegerField(blank=True, default=0, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_last_sale', models.DateTimeField(auto_now=True, null=True)),
                ('count_of_sold', models.IntegerField(blank=True, default=0, null=True)),
                ('length', models.FloatField(blank=True, default=0, null=True)),
                ('curve', models.CharField(blank=True, default=0, max_length=15, null=True)),
                ('color', models.CharField(blank=True, default=0, max_length=25, null=True)),
                ('thickness', models.FloatField(blank=True, default=0, null=True)),
                ('coupling_speed', models.FloatField(blank=True, default=0, null=True)),
                ('capacity', models.IntegerField(blank=True, default=0, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subcategories.subcategory')),
            ],
            options={
                'ordering': ['-timestamp', '-date_last_sale'],
            },
        ),
    ]
